name: Release

# This workflow follows Pypi guidelines for publishing using trusted publishers
# See https://docs.pypi.org/trusted-publishers/using-a-publisher/ for more details.

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  package:
    name: Package
    uses: ./.github/workflows/package.yml

  release:
    name: Release
    needs: [package]
    runs-on: ubuntu-latest

    # Make the GH environment explicit
    environment: release

    permissions:
      # Mandatory for attaching assets to releases
      contents: write
      # Mandatory for trusted publishing
      id-token: write

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: python-package-distributions
        path: dist/

    # The assets can be attached to an existing release, if a matching tag is found
    - name: Upload release assets
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
      with:
        files: dist/*.whl

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
